# Generated by Django 3.0.5 on 2020-05-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_availabe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
